### ISSUE TITLE
18-06-2020 Team-104-the-Fornax

### ISSUE THREAD

**Issue by MrSayyod** [Morrism1/tic-tac-toe#3]
Nice job!
Recommendations:
1. You have used `puts` on your user.rb. Please, do remember that all prompts, suggestions should be in the main.rb.
2. Board is displaying numbers when you run the game. When the user makes a choice, numbers are moving instead of replacing. Please, fix this.
3. Please, add the logic that prevents players from selecting the same symbol.

**Comment by tacodtripe** [comment]
Done man, thanks.
